movies/urls.py
from django.urls import path
from . import views
# movies
# movies/1/details
app_name='movies'

urlpatterns=[
path('', views.index, name='index'),
path('<int:movie_id>', views.detail, name='detail')
]

vidly/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from . import views
import movies

movie_resource=MovieResource()
urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resource.urls))
]

api/models.py
from importlib import resources
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie
# Create your models here.
#we need to add model
class MovieResource(ModelResource):
    class Meta:
        queryset=Movie.objects.all()
        resource_name='movies'
        excludes=['data_created']

movies/models.py
from datetime import datetime
from platform import release
from time import time
from django.db import models
from django.utils import timezone

# Create your models here.
class Genre(models.Model):
    name= models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title=models.CharField(max_length=255)
    release_year=models.IntegerField()
    number_in_stock= models.IntegerField()
    daily_rate=models.FloatField()
    genre=models.ForeignKey(Genre, on_delete=models.CASCADE)
    data_created = models.DateTimeField(default=timezone.now)

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
import re
from warnings import catch_warnings
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import Movie

# Create your views here.
def index(request):
    movies=Movie.objects.all()
    output= ', '.join([m.title for m in movies])
    return render(request, 'movies/index.html', {'movies': movies})
    
def detail(request, movie_id):   
    movie= get_object_or_404(Movie, pk=movie_id)
    return render(request, 'movies/detail.html', {'movie': movie})

vidly/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
    <dl>
        <dt>Title</dt>
        <dd>{{ movie.title }}</dd>
        <dt>{{Genre}}</dt>
        <dd>{{ movie.genre }}</dd>
        <dt>Stock</dt>
        <dd>{{ movie.number_in_stock }}</dd>
    </dl>
{% endblock  %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Genre</th>
                <th>Stock</th>
                <th>Daily Rate</th>
            </tr>
        </thead>
        <tbody>
            {% for movie in movies %}
            <tr>
                <td>
                    <a href="{% url 'movies:detail' movie.id %}">{{movie.title}}</a>
                  
                </td>
                <td>{{ movie.genre }}</td>
                <td>{{ movie.number_in_stock }}</td>
                <td>{{ movie.daily_rate }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock  %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Vidly</title>
  </head>
  <body>
      <!-- As a link -->
        <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
        <a class="navbar-brand" href="#">Vidly</a>
        </div>
        </nav>
        <main class= "container">
            {% block content %}
            
            {% endblock %}
        </main>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/home.html
{% extends 'base.html' %}


{% block content %}
<a href="{% url 'movies:index'%}">Movies</a>
{% endblock  %}